---
- name: Fedora VM - destroy all
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yml

  tasks:
    - name: Check if work directory exists
      ansible.builtin.stat:
        path: "{{ vm_tf_dir }}"
      register: tf_dir_stat

    - name: OpenTofu destroy (remove VM, network, pool)
      ansible.builtin.command:
        cmd: tofu destroy -auto-approve
        chdir: "{{ vm_tf_dir }}"
      when: tf_dir_stat.stat.exists
      register: tf_destroy
      failed_when: false
      changed_when: tf_destroy.rc == 0 and 'Destroy complete!' in tf_destroy.stdout

    - name: Stop VM domain if running
      ansible.builtin.command:
        cmd: virsh -c qemu:///system destroy {{ vm_prefix }}_vm0
      failed_when: false
      changed_when: false

    - name: Undefine VM domain from libvirt if not tracked by tofu
      ansible.builtin.command:
        cmd: virsh -c qemu:///system undefine --nvram {{ vm_prefix }}_vm0
      failed_when: false
      changed_when: false

    - name: Destroy network from libvirt if not tracked by tofu
      ansible.builtin.command:
        cmd: virsh -c qemu:///system net-destroy {{ vm_prefix }}_network
      failed_when: false
      changed_when: false

    - name: Undefine network from libvirt if not tracked by tofu
      ansible.builtin.command:
        cmd: virsh -c qemu:///system net-undefine {{ vm_prefix }}_network
      failed_when: false
      changed_when: false

    - name: Destroy storage pool from libvirt if not tracked by tofu
      ansible.builtin.command:
        cmd: virsh -c qemu:///system pool-destroy {{ vm_prefix }}
      failed_when: false
      changed_when: false

    - name: Undefine storage pool from libvirt if not tracked by tofu
      ansible.builtin.command:
        cmd: virsh -c qemu:///system pool-undefine {{ vm_prefix }}
      failed_when: false
      changed_when: false

    - name: Remove base directory (pool, work)
      ansible.builtin.file:
        path: "{{ vm_base_dir }}"
        state: absent
      become: true
